module.exports = {
  plugins: {
    "postcss-preset-env": {
      browsers: `last 2 versions`,
      stage: 0,
    },
    "postcss-pxtorem": {
      rootValue: 26,
      unitPrecision: 5,
      propList: ["*"],
      selectorBlackList: [],
      replace: true,
      mediaQuery: false,
      minPixelValue: 0,
      exclude: /node_modules/i,
    },
    // "postcss-px-to-viewport": {
    //   unitToConvert: "px",
    //   viewportWidth: 750,
    //   unitPrecision: 5,
    //   propList: ["*"],
    //   viewportUnit: "vw",
    //   fontViewportUnit: "vw",
    //   selectorBlackList: [],
    //   minPixelValue: 1,
    //   mediaQuery: false,
    //   replace: false,
    //   exclude: undefined,
    //   include: undefined,
    //   landscape: false,
    //   landscapeUnit: "vw",
    //   landscapeWidth: 568,
    // },
  },
};
